name = "fullstack-backend"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"