name = "fullstack-backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
MY_VARIABLE = "production_value"
FIREBASE_PROJECT_ID = "your_project_id_here"

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "local-todo-db"
migrations_dir = "migrations"